image: registry.5xruby.tw/elct9620/gitlab-unity3d-image-apk

variables:
  DEBIAN_FRONTEND: noninteractive

build:apk:
  before_script:
    - apt-get install -qq -y xorg xvfb
    - mkdir -p /root/.cache/unity3d
    - mkdir -p /root/.local/share/unity3d/Unity
    # Unity 2017+
    - echo $UNITY_LICENSE_CONTENT > /root/.local/share/unity3d/Unity/Unity_lic.ulf
    - cat /root/.local/share/unity3d/Unity/Unity_lic.ulf
  script: |
    mkdir -p ./Builds
    xvfb-run --server-args="-screen - 1024x768x24" \
    /usr/local/unity3d/Editor/Unity \
      -projectPath $(pwd) \
      -quit \
      -batchmode \
      -buildTarget Android \
      -customBuildTarget Android \
      -customBuildPath ./Builds \
      -customBuildOptions AcceptExternalModificationsToPlayer \
      -executeMethod BuildCommand.PerformBuild \
      -logFile
  artifacts:
    paths:
      - ./Builds



